version: "3.9"
services:
  reminders:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./reminders:/reminders
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
      sh -c "celery -A reminders worker -B"
